/**
 * tmux.ts — thin wrapper around tmux CLI for session lifecycle management.
 *
 * All functions are synchronous (execSync) because they are fast local
 * operations and the VS Code terminal API that consumes them is synchronous.
 *
 * Every tmux invocation uses a dedicated socket (`-L persisterm`) so that
 * persistent terminals are fully isolated from the user's own tmux sessions.
 * A custom config file disables the status bar, turns off the alternate
 * screen buffer (so that VS Code's native scrollback works normally), and
 * eliminates the escape-key delay.
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { isSessionForPrefix } from "./session-names";

/* ------------------------------------------------------------------ */
/*  Dedicated socket & configuration                                   */
/* ------------------------------------------------------------------ */

/** Socket name — keeps persisterm sessions separate from user tmux. */
export const SOCKET = "persisterm";

const CONFIG_DIR = path.join(os.homedir(), ".config", "persisterm");
const CONFIG_PATH = path.join(CONFIG_DIR, "tmux.conf");
const VSCODE_ENV_PATH = path.join(CONFIG_DIR, "vscode-env.sh");
const SHELL_LAUNCHER_PATH = path.join(CONFIG_DIR, "shell-launcher.sh");
const ZSH_INIT_DIR = path.join(CONFIG_DIR, "zsh");
const FISH_INIT_PATH = path.join(CONFIG_DIR, "fish-init.fish");
const PROXY_PATH = path.join(CONFIG_DIR, "tmux-proxy.py");

/**
 * Environment variables that VS Code sets for its integrated terminal
 * and that must be propagated into tmux sessions so that `code --wait`,
 * git credential helpers, and other VS Code integrations keep working
 * across reconnects.
 */
const TMUX_DEFAULT_ENV_VARS = [
  "DISPLAY",
  "KRB5CCNAME",
  "MSYSTEM",
  "SSH_ASKPASS",
  "SSH_AUTH_SOCK",
  "SSH_AGENT_PID",
  "SSH_CONNECTION",
  "WAYLAND_DISPLAY",
  "WINDOWID",
  "XAUTHORITY",
  "XDG_CURRENT_DESKTOP",
  "XDG_SESSION_DESKTOP",
  "XDG_SESSION_TYPE",
];

const VSCODE_ENV_VARS = [
  "VSCODE_IPC_HOOK_CLI",
  "VSCODE_GIT_IPC_HANDLE",
  "VSCODE_GIT_ASKPASS_NODE",
  "VSCODE_GIT_ASKPASS_MAIN",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS",
  "BROWSER",
  "GIT_ASKPASS",
];

/** Return the user's SSH/login shell, with a safe POSIX fallback. */
export function resolveUserShell(): string {
  const candidates = [process.env["SHELL"], os.userInfo().shell, "/bin/sh"];
  for (const candidate of candidates) {
    if (!candidate || !path.isAbsolute(candidate)) {
      continue;
    }
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return candidate;
    } catch { /* try the next candidate */ }
  }
  return "/bin/sh";
}

/** Build the isolated tmux config for a specific user login shell. */
export function buildTmuxConfig(
  userShell: string,
  shellLauncherPath = SHELL_LAUNCHER_PATH,
): string {
  const launchCommand = `${esc(shellLauncherPath)} ${esc(userShell)}`;
  return `\
# Persisterm tmux configuration
# Auto-generated on every activation — manual edits will be overwritten.

# Hide the tmux status bar (VS Code already shows which terminal is active)
set-option -g status off

# Zero escape-key delay (critical for vim / emacs users)
set-option -g escape-time 0

# ── Scrollback ───────────────────────────────────────────────────────
# Generous scrollback inside tmux.  The proxy uses capture-pane to
# replay this buffer into VS Code's native scrollback on reconnect.
set-option -g history-limit 50000

# ── VS Code integration ─────────────────────────────────────────────
# Preserve tmux's standard SSH/display variables and add the VS Code
# integration variables supplied by the attaching proxy process.
set-option -g update-environment "${[...TMUX_DEFAULT_ENV_VARS, ...VSCODE_ENV_VARS].join(" ")}"

# Use /bin/sh only to exec the launcher, avoiding an extra user-shell startup
# pass (notably a duplicate .zshenv). The pane ends up running the user's shell.
set-option -g default-shell "/bin/sh"
set-option -g default-command ${tmuxQuote(launchCommand)}
`;
}


export interface ShellIntegrationFiles {
  launcher: string;
  zshEnv: string;
  zshProfile: string;
  zshRc: string;
  zshLogin: string;
  fishInit: string;
}

/**
 * Build shell startup shims. They preserve the user's native startup-file
 * order and add the refresh hook only after the user's configuration ran.
 */
export function buildShellIntegrationFiles(
  vscodeEnvPath = VSCODE_ENV_PATH,
  zshInitDir = ZSH_INIT_DIR,
  fishInitPath = FISH_INIT_PATH,
): ShellIntegrationFiles {
  const env = esc(vscodeEnvPath);
  const zshDir = esc(zshInitDir);
  const fishCommand = esc(`source ${fishQuote(fishInitPath)}`);
  const fishRuntimeDir = fishQuote(
    process.env["XDG_RUNTIME_DIR"] || `/run/user/${process.getuid!()}`,
  );

  const launcher = `#!/bin/sh
# Auto-generated by Persisterm — do not edit.
shell=$1
[ -n "$shell" ] || shell=/bin/sh

case "\${shell##*/}" in
  bash)
    # PROMPT_COMMAND is exported before Bash starts. This keeps real login-shell
    # semantics; well-behaved profile files preserve the inherited hook.
    case "\${PROMPT_COMMAND-}" in
      *vscode-env.sh*) ;;
      *) PROMPT_COMMAND=". ${env} 2>/dev/null\${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
    esac
    export PROMPT_COMMAND
    exec "$shell" -l
    ;;
  zsh)
    if [ "\${ZDOTDIR+x}" = x ]; then
      export PERSISTERM_USER_ZDOTDIR="$ZDOTDIR"
      export PERSISTERM_USER_ZDOTDIR_SET=1
    else
      export PERSISTERM_USER_ZDOTDIR="$HOME"
      export PERSISTERM_USER_ZDOTDIR_SET=0
    fi
    export ZDOTDIR=${zshDir}
    exec "$shell" -l
    ;;
  fish)
    exec "$shell" -l -C ${fishCommand}
    ;;
  *)
    # Unknown shells still get their normal login startup files and inherit
    # the current VS Code environment resolved before tmux was attached.
    exec "$shell" -l
    ;;
esac
`;

  function zshUserFile(name: string): string {
    return `# Auto-generated by Persisterm — do not edit.
if [[ $options[norcs] = off && -f "$PERSISTERM_USER_ZDOTDIR/${name}" ]]; then
  _persisterm_user_zdotdir=$PERSISTERM_USER_ZDOTDIR
  _persisterm_wrapper_zdotdir=$ZDOTDIR
  if [[ $PERSISTERM_USER_ZDOTDIR_SET == 1 ]]; then
    ZDOTDIR=$_persisterm_user_zdotdir
  else
    unset ZDOTDIR
  fi
  if [[ "$_persisterm_user_zdotdir" != "$_persisterm_wrapper_zdotdir" ]]; then
    . "$_persisterm_user_zdotdir/${name}"
  fi
  if (( \${+ZDOTDIR} )); then
    export PERSISTERM_USER_ZDOTDIR="$ZDOTDIR"
    export PERSISTERM_USER_ZDOTDIR_SET=1
  else
    export PERSISTERM_USER_ZDOTDIR="$HOME"
    export PERSISTERM_USER_ZDOTDIR_SET=0
  fi
  ZDOTDIR=$_persisterm_wrapper_zdotdir
  unset _persisterm_user_zdotdir _persisterm_wrapper_zdotdir
fi
`;
  }

  const zshLogin = `${zshUserFile(".zlogin")}
. ${env} 2>/dev/null
builtin autoload -Uz add-zsh-hook
add-zsh-hook precmd _persisterm_refresh
if [[ $PERSISTERM_USER_ZDOTDIR_SET == 1 ]]; then
  ZDOTDIR=$PERSISTERM_USER_ZDOTDIR
else
  unset ZDOTDIR
fi
unset PERSISTERM_USER_ZDOTDIR PERSISTERM_USER_ZDOTDIR_SET
`;

  const fish = `# Auto-generated by Persisterm — do not edit.
function _persisterm_refresh --on-event fish_prompt
  set -l _s (command ls -t ${fishRuntimeDir}/vscode-ipc-*.sock 2>/dev/null | command head -n 1)
  test -n "$_s"; and set -gx VSCODE_IPC_HOOK_CLI "$_s"
  set _s (command ls -t ${fishRuntimeDir}/vscode-git-*.sock 2>/dev/null | command head -n 1)
  test -n "$_s"; and set -gx VSCODE_GIT_IPC_HANDLE "$_s"

  if not test -x "$BROWSER"; or not test -x "$GIT_ASKPASS"
    for _vsr in "$HOME/.vscode-server" "$HOME/.vscode-server-insiders" "$HOME/.cursor-server" "$HOME/.windsurf-server" "$HOME/.vscode-server-oss"
      test -d "$_vsr/cli/servers"; or continue
      set -l _c (command grep -oE '(Stable|Insider)-[0-9a-f]+' "$_vsr/cli/servers/lru.json" 2>/dev/null | command head -n 1)
      set -l _srv "$_vsr/cli/servers/$_c/server"
      if test -z "$_c"; or not test -d "$_srv"
        set _c (command ls -t "$_vsr/cli/servers" 2>/dev/null | command grep -E '^(Stable|Insider)-' | command head -n 1)
        set _srv "$_vsr/cli/servers/$_c/server"
      end
      test -n "$_c"; and test -d "$_srv"; or continue
      test -x "$_srv/bin/helpers/browser.sh"; and set -gx BROWSER "$_srv/bin/helpers/browser.sh"
      test -x "$_srv/extensions/git/dist/askpass.sh"; and set -gx GIT_ASKPASS "$_srv/extensions/git/dist/askpass.sh"
      test -f "$_srv/extensions/git/dist/askpass-main.js"; and set -gx VSCODE_GIT_ASKPASS_MAIN "$_srv/extensions/git/dist/askpass-main.js"
      test -x "$_srv/node"; and set -gx VSCODE_GIT_ASKPASS_NODE "$_srv/node"
      break
    end
  end
end

_persisterm_refresh
`;

  return {
    launcher,
    zshEnv: zshUserFile(".zshenv"),
    zshProfile: zshUserFile(".zprofile"),
    zshRc: zshUserFile(".zshrc"),
    zshLogin,
    fishInit: fish,
  };
}

/**
 * Write (or overwrite) the persisterm tmux config file.
 * Call once during extension activation.
 */
export function ensureConfig(): void {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });

  const newConfig = buildTmuxConfig(resolveUserShell());

  // Detect changes so a running server can reload them without destroying
  // persistent sessions. Existing panes keep their current shell; newly
  // created panes use the updated shell launcher.
  let configChanged = false;
  try {
    const existing = fs.readFileSync(CONFIG_PATH, "utf-8");
    configChanged = existing !== newConfig;
  } catch {
    configChanged = true; // no existing config
  }

  fs.writeFileSync(CONFIG_PATH, newConfig, { encoding: "utf-8" });

  if (configChanged) {
    try {
      execSync(`tmux -L ${SOCKET} source-file ${esc(CONFIG_PATH)} 2>/dev/null`, {
        stdio: "pipe",
      });
    } catch { /* server wasn't running — it will read the file on startup */ }
  }

  // Clean up stale tmux socket if the server is dead.  A stale socket
  // causes tmux to fail with "server exited unexpectedly" (exit code 1).
  try {
    execSync(`tmux -L ${SOCKET} list-sessions 2>/dev/null`, { stdio: "pipe" });
  } catch {
    // Server isn't running — remove the socket if it exists.
    const socketDir = `/tmp/tmux-${process.getuid!()}`;
    const socketPath = path.join(socketDir, SOCKET);
    try {
      fs.unlinkSync(socketPath);
    } catch { /* socket doesn't exist — fine */ }
  }

  const shellFiles = buildShellIntegrationFiles();
  fs.mkdirSync(ZSH_INIT_DIR, { recursive: true });
  fs.writeFileSync(SHELL_LAUNCHER_PATH, shellFiles.launcher, {
    encoding: "utf-8",
    mode: 0o755,
  });
  fs.chmodSync(SHELL_LAUNCHER_PATH, 0o755);
  fs.writeFileSync(path.join(ZSH_INIT_DIR, ".zshenv"), shellFiles.zshEnv, { encoding: "utf-8" });
  fs.writeFileSync(path.join(ZSH_INIT_DIR, ".zprofile"), shellFiles.zshProfile, { encoding: "utf-8" });
  fs.writeFileSync(path.join(ZSH_INIT_DIR, ".zshrc"), shellFiles.zshRc, { encoding: "utf-8" });
  fs.writeFileSync(path.join(ZSH_INIT_DIR, ".zlogin"), shellFiles.zshLogin, { encoding: "utf-8" });
  fs.writeFileSync(FISH_INIT_PATH, shellFiles.fishInit, { encoding: "utf-8" });
}

/**
 * Write the tmux control-mode proxy script to the config directory.
 *
 * The proxy bridges VS Code's terminal pty and tmux's control mode,
 * giving native VS Code scrollback while tmux handles persistence.
 */
export function ensureProxy(): void {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  const src = path.join(__dirname, "..", "src", "tmux-proxy.py");
  // Try reading from the source tree first (development), then fall
  // back to reading from next to the compiled JS (packaged extension).
  let content: string;
  try {
    content = fs.readFileSync(src, "utf-8");
  } catch {
    const alt = path.join(__dirname, "tmux-proxy.py");
    content = fs.readFileSync(alt, "utf-8");
  }
  fs.writeFileSync(PROXY_PATH, content, { encoding: "utf-8", mode: 0o755 });
}

/**
 * Write the VS Code env helper script.  Every value is resolved
 * dynamically at runtime (never snapshotted from process.env, which is
 * stale inside the extension host and never updated after a reload), so
 * the script stays correct across both reconnects and server updates:
 *
 *   - VSCODE_IPC_HOOK_CLI / VSCODE_GIT_IPC_HANDLE — the live IPC sockets,
 *     which rotate on every VS Code reconnect.
 *   - BROWSER / GIT_ASKPASS / VSCODE_GIT_ASKPASS_{NODE,MAIN} — helper
 *     scripts under the active server build, which vanish when an update
 *     deletes the old build out from under a long-lived tmux session
 *     (breaking `az login`'s browser launch and git credential prompts).
 *
 * Shell-specific startup shims call `_persisterm_refresh` on every prompt,
 * so a running shell self-heals after reconnects and server updates.
 */
export function writeVscodeEnv(): void {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });

  // Detect the XDG_RUNTIME_DIR (where sockets live).  Usually /run/user/<uid>.
  const runtimeDir = process.env["XDG_RUNTIME_DIR"] || `/run/user/${process.getuid!()}`;

  const script = `#!/bin/sh
# Auto-generated by Persisterm — do not edit.
# Sourced inside tmux sessions to keep VS Code integrations working.
#
# All values are resolved dynamically so the shell self-heals across both
# VS Code reconnects (sockets rotate) and server updates (helper scripts
# move to a new build directory and the old one is deleted):
#   * VSCODE_IPC_HOOK_CLI / VSCODE_GIT_IPC_HANDLE — live IPC sockets.
#   * BROWSER / GIT_ASKPASS / VSCODE_GIT_ASKPASS_* — helper scripts under
#     the active server build (BROWSER drives \`az login\`'s browser launch;
#     GIT_ASKPASS drives git credential prompts).

_persisterm_refresh() {
  # Live IPC + git sockets — newest wins; they rotate on every reconnect.
  _s=$(ls -t '${runtimeDir}'/vscode-ipc-*.sock 2>/dev/null | head -1)
  [ -n "$_s" ] && export VSCODE_IPC_HOOK_CLI="$_s"
  _s=$(ls -t '${runtimeDir}'/vscode-git-*.sock 2>/dev/null | head -1)
  [ -n "$_s" ] && export VSCODE_GIT_IPC_HANDLE="$_s"

  # Server-build-specific helpers. Only re-derive when the current paths
  # have gone missing (e.g. an update deleted the old build), then locate
  # the active build via its most-recently-used list (fall back to newest).
  if [ ! -x "$BROWSER" ] || [ ! -x "$GIT_ASKPASS" ]; then
    for _vsr in "$HOME/.vscode-server" "$HOME/.vscode-server-insiders" "$HOME/.cursor-server" "$HOME/.windsurf-server" "$HOME/.vscode-server-oss"; do
      [ -d "$_vsr/cli/servers" ] || continue
      _c=$(grep -oE '(Stable|Insider)-[0-9a-f]+' "$_vsr/cli/servers/lru.json" 2>/dev/null | head -1)
      _srv="$_vsr/cli/servers/$_c/server"
      if [ -z "$_c" ] || [ ! -d "$_srv" ]; then
        _c=$(ls -t "$_vsr/cli/servers" 2>/dev/null | grep -E '^(Stable|Insider)-' | head -1)
        _srv="$_vsr/cli/servers/$_c/server"
      fi
      [ -n "$_c" ] && [ -d "$_srv" ] || continue
      [ -x "$_srv/bin/helpers/browser.sh" ] && export BROWSER="$_srv/bin/helpers/browser.sh"
      [ -x "$_srv/extensions/git/dist/askpass.sh" ] && export GIT_ASKPASS="$_srv/extensions/git/dist/askpass.sh"
      [ -f "$_srv/extensions/git/dist/askpass-main.js" ] && export VSCODE_GIT_ASKPASS_MAIN="$_srv/extensions/git/dist/askpass-main.js"
      [ -x "$_srv/node" ] && export VSCODE_GIT_ASKPASS_NODE="$_srv/node"
      break
    done
  fi
}

# Resolve once during startup. Shell-specific init files also register this
# function as their prompt hook for reconnects and server updates.
_persisterm_refresh
`;

  fs.writeFileSync(VSCODE_ENV_PATH, script, { encoding: "utf-8" });
}

/** Common prefix for every tmux CLI invocation. */
function baseCmd(): string {
  return `tmux -f ${esc(CONFIG_PATH)} -L ${SOCKET}`;
}

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface TmuxSession {
  name: string;
  /** Number of clients currently attached to this session. */
  attached: number;
  windows: number;
  /** Unix epoch seconds when the session was created. */
  created: number;
}

/* ------------------------------------------------------------------ */
/*  Queries                                                            */
/* ------------------------------------------------------------------ */

/** Return `true` when the `tmux` binary is on $PATH. */
export function isInstalled(): boolean {
  try {
    execSync("command -v tmux", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/** Return the tmux version as a numeric tuple, e.g. [3, 4] for "3.4". */
export function version(): [number, number] | undefined {
  try {
    const raw = execSync("tmux -V", { encoding: "utf-8", stdio: "pipe" }).trim();
    const m = raw.match(/(\d+)\.(\d+)/);
    if (m) {
      return [parseInt(m[1], 10), parseInt(m[2], 10)];
    }
  } catch { /* ignore */ }
  return undefined;
}

/**
 * List every tmux session whose name has the exact form `<prefix>-N`.
 * Returns an empty array when the tmux server is not running.
 */
export function listSessions(prefix: string): TmuxSession[] {
  try {
    const raw = execSync(
      `${baseCmd()} list-sessions -F "#{session_name}|#{session_attached}|#{session_windows}|#{session_created}" 2>/dev/null`,
      { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
    );
    return raw
      .trim()
      .split("\n")
      .filter((l) => l.length > 0)
      .map((line) => {
        const [name, attached, windows, created] = line.split("|");
        return {
          name,
          attached: parseInt(attached, 10),
          windows: parseInt(windows, 10),
          created: parseInt(created, 10),
        };
      })
      .filter((s) => isSessionForPrefix(s.name, prefix));
  } catch {
    return [];
  }
}

/** Check whether a specific tmux session exists. */
export function hasSession(name: string): boolean {
  try {
    execSync(`${baseCmd()} has-session -t ${esc(name)} 2>/dev/null`, {
      stdio: "pipe",
    });
    return true;
  } catch {
    return false;
  }
}

/* ------------------------------------------------------------------ */
/*  Mutations                                                          */
/* ------------------------------------------------------------------ */

/** Kill a single tmux session.  Returns `true` on success. */
export function killSession(name: string): boolean {
  try {
    execSync(`${baseCmd()} kill-session -t ${esc(name)}`, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/**
 * Find the lowest non-negative integer N such that
 * `${prefix}-${N}` does not already exist as a tmux session.
 */
export function nextIndex(prefix: string): number {
  const sessions = listSessions(prefix);
  const taken = new Set(
    sessions
      .map((s) => {
        const m = s.name.match(
          new RegExp(`^${escapeRegex(prefix)}-(\\d+)$`),
        );
        return m ? parseInt(m[1], 10) : -1;
      })
      .filter((i) => i >= 0),
  );
  let i = 0;
  while (taken.has(i)) {
    i++;
  }
  return i;
}

/**
 * Build the shell invocation that creates-or-attaches a tmux session
 * via the control-mode proxy.
 *
 * The proxy script (`tmux-proxy.py`) uses tmux's `-CC` control mode to
 * bridge between VS Code's terminal pty and the tmux session.  This
 * gives native VS Code scrollback while tmux handles persistence.
 *
 * Before launching the proxy we:
 *   1. Source the VS Code env file (so env vars propagate to tmux).
 *   2. For existing sessions, push each env var into the tmux session
 *      via `tmux set-environment` (completely invisible).
 *
 * When `reattach` is true the proxy dumps the pane's scrollback history
 * into VS Code's terminal before connecting, so the user sees their
 * previous output in the native scrollback.
 *
 * An auto-reconnect loop wraps the proxy invocation: if the proxy
 * exits unexpectedly but the tmux session is still alive (e.g. a
 * transient error during reconnection), the shell retries up to 5
 * times with a one-second delay between attempts.  `--reattach` is
 * only passed on the first attempt (scrollback was already replayed).
 */
export function shellCommand(
  sessionName: string,
  reattach = false,
): {
  shellPath: string;
  shellArgs: string[];
} {
  const base = `tmux -f ${esc(CONFIG_PATH)} -L ${SOCKET}`;
  const envFile = esc(VSCODE_ENV_PATH);
  const sess = esc(sessionName);

  // Build set-environment commands for each tracked variable.
  const setEnvCmds = VSCODE_ENV_VARS.map(
    (v) => `    ${base} set-environment -t ${sess} ${v} "\$${v}" 2>/dev/null`,
  ).join("\n");

  const proxyArgs = [
    esc(PROXY_PATH),
    sess,
    "--socket", SOCKET,
    "--config", esc(CONFIG_PATH),
  ];
  const proxyCmd = `python3 ${proxyArgs.join(" ")}`;
  // First attempt may replay scrollback history.
  const firstCmd = reattach ? `${proxyCmd} --reattach` : proxyCmd;

  const cmd = [
    // Exit cleanly on SIGTERM/SIGHUP (VS Code closing the terminal tab).
    `trap 'exit 0' TERM HUP`,
    // 1. Source VS Code env into this shell
    `. ${envFile} 2>/dev/null`,
    // 2. If session exists, silently push env vars into the session
    `if ${base} has-session -t ${sess} 2>/dev/null; then`,
    setEnvCmds,
    `fi`,
    // 3. Launch the proxy (first attempt may replay scrollback)
    firstCmd,
    // 4. Auto-reconnect: if the proxy exits but the tmux session is
    //    still alive, the connection was interrupted — retry.
    `_pn=0`,
    `while ${base} has-session -t ${sess} 2>/dev/null; do`,
    `  _pn=$((_pn + 1))`,
    `  [ $_pn -ge 5 ] && printf '\\033[33mPersisterm: giving up after 5 reconnect attempts.\\033[0m\\n' && break`,
    `  printf '\\033[33mPersisterm: reconnecting (attempt %d/5)...\\033[0m\\n' "$_pn"`,
    `  sleep 1`,
    `  ${proxyCmd}`,
    `done`,
  ].join("\n");

  return {
    shellPath: "sh",
    shellArgs: ["-c", cmd],
  };
}

/* ------------------------------------------------------------------ */
/*  Internal utilities                                                 */
/* ------------------------------------------------------------------ */

/** Shell-escape a session name for use in tmux CLI invocations. */
function esc(name: string): string {
  // Session names are alphanumeric + dash in our scheme, but be safe.
  return `'${name.replace(/'/g, "'\\''")}'`;
}

function tmuxQuote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function fishQuote(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
